import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import RequestACall from "@/components/RequestACall";
import WhatWeMove from "@/components/WhatWeMove";
import WhatWeDo from "@/components/WhatWeDo";
import FaqSection from "@/components/FaqSection";
import CallbackForm from "@/components/CallbackForm";
import Footer from "@/components/Footer";
import Testimonials from "@/components/Testimonials";
import KeepMoving from "@/components/KeepMoving";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Truck Dispatch Experts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
